We have a bug with equation: 

\begin{align} 
-k^3 + k^2 + 5 k + 3 &= 0
\end{align}

The equiation have trivial solution, k = 3 and k = -1. 

Let's check it.

In [8]:
def k_test(k):
    return -(k)**3+k**2+5*k+3

In [13]:
print(k_test(3.0),k_test(3))
print(k_test(-1.0),k_test(-1))

0.0 0
0.0 0


How you can see - everithing is ok. Test same thing with numpy.roots fuction

In [15]:
import numpy as np
l = [-1,1,5,3]
np.roots(l)

array([ 3. +0.00000000e+00j, -1. +1.20320638e-08j, -1. -1.20320638e-08j])

In [16]:
l_f = [-1.0,1.0,5.0,3.0]
np.roots(l_f)

array([ 3. +0.00000000e+00j, -1. +1.20320638e-08j, -1. -1.20320638e-08j])

In [20]:
l_a = np.array(l_f)
l_a

array([-1.,  1.,  5.,  3.])

In [21]:
np.roots(l_a)

array([ 3. +0.00000000e+00j, -1. +1.20320638e-08j, -1. -1.20320638e-08j])

Slightly different, isn't it?

In [18]:
np.version.full_version

'1.13.0rc1'